apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: todoapp
        image: devopstraning1235/todoapp:replaceImageTag
        ports:
        - containerPort: 4000
